name: Build and Deploy
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build_windows:
    name: Windows Client
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./system_theme/example
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: git config --system core.longpaths true
      - name: Flutter Pub Get
        run: flutter pub get
      - name: Build for Windows
        run: flutter build windows --verbose

  build_android:
    name: Android Client
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./system_theme/example
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build apk --verbose --split-per-abi
      - run: flutter build appbundle --verbose

  build_iOS:
    name: iOS Client
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: ./system_theme/example
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: "stable"
          architecture: x64
          cache: true

      - run: flutter pub get
      - run: flutter build ios --verbose --release --no-codesign
      - run: flutter build ipa --verbose --release --no-codesign

  build_macOS:
    name: macOS Client
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: ./system_theme/example
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: "stable"
          architecture: x64
          cache: true

      - run: flutter pub get
      - run: flutter build macos

  build_linux:
    name: Linux Client
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./system_theme/example
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - run: sudo apt-get update -y
      - run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev mpv libmpv-dev dpkg-dev p7zip-full p7zip-rar
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build linux --verbose

  build_web:
    name: Web Client
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./system_theme/example
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build web --verbose
